version: "3.8"
services:
  my-react-app:
    container_name: my-react-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/usr/src/app
        - node_modules:/usr/src/app/node_modules
